Repository inbarbc/StockMarket_Project, pull requests merged in 2024-06, with the labels that each got.

#275 fixed requestToEnterSystem in SystemService to not receive a token, a…
  src/main/java/Server/SystemMappings.java
  src/main/java/ServiceLayer/SystemService.java
  src/test/java/AcceptanceTests/Implementor/RealBridge.java
Labels: bug

#277 deleted duplicate test libraries in pom.xml
  pom.xml
Labels: bug

#279 add age to user for policy
  src/main/java/Domain/Facades/UserFacade.java
  src/main/java/Domain/User.java
  src/main/java/Server/UserMappings.java
  src/main/java/ServiceLayer/UserService.java
  src/test/java/AcceptanceTests/Implementor/RealBridge.java
  src/test/java/DmainTests/ShopFacadeTests.java
  src/test/java/DmainTests/UserFacadeTests.java
  src/test/java/DmainTests/UserTests.java
Labels: start first with

#280 add validation of email to user
  src/main/java/Domain/Authenticators/EmailValidator.java
  src/main/java/Domain/Authenticators/PasswordEncoderUtil.java
  src/main/java/Domain/Facades/UserFacade.java
  src/main/java/ServiceLayer/UserService.java
  src/test/java/AcceptanceTests/Implementor/RealBridge.java
  src/test/java/AcceptanceTests/ProjectTests/GuestAcceptanceTests.java
  src/test/java/AcceptanceTests/ProjectTests/ShoppingUserAcceptanceTests.java
  src/test/java/DmainTests/ShopFacadeTests.java
  src/test/java/DmainTests/ShopTests.java
  src/test/java/DmainTests/UserFacadeTests.java
  src/test/java/DmainTests/UserTests.java
Labels: start first with

#332 added auto generator for the order id.
  pom.xml
  src/main/java/Domain/Order.java
  src/test/java/DmainTests/UserFacadeTests.java
  src/test/java/DmainTests/UserTests.java
Labels: can wait for later

#333 add auto generator for shop order.
  src/main/java/Domain/ShopOrder.java
  src/test/java/DmainTests/ShopFacadeTests.java
Labels: can wait for later

#338 logout button was added
  src/main/java/UI/views/HeaderComponent.java
Labels: can wait for later

#339 Added a DTO for the external service and implemented the necessary ch…
  frontend/generated/flow/generated-flow-imports.d.ts
  frontend/generated/flow/generated-flow-imports.js
  frontend/generated/flow/generated-flow-webcomponent-imports.js
  frontend/generated/jar-resources/icons/icon.png
  frontend/generated/jar-resources/images/empty-plant.png
  frontend/generated/jar-resources/styles/shared-styles.css
  frontend/generated/theme.d.ts
  frontend/generated/theme.js
  frontend/generated/vaadin.ts
  src/main/java/Domain/ExternalServices/ExternalServiceHandler.java
  src/main/java/Dtos/ExternalServiceDto.java
  src/main/java/ServiceLayer/SystemService.java
  src/test/java/AcceptanceTests/Implementor/RealBridge.java
  src/test/java/DmainTests/ExternalServicesTests.java
Labels: can wait for later

#350 finish system AT
  src/test/java/AcceptanceTests/Implementor/RealBridge.java
  src/test/java/AcceptanceTests/ProjectTests/SystemAcceptanceTests.java
Labels: can wait for later

#352 fix add rating to shop function and tests
  src/main/java/Domain/Shop.java
  src/test/java/AcceptanceTests/Implementor/ProxyBridge.java
  src/test/java/DmainTests/ShopTests.java
Labels: can wait for later

#477 469 UI appoint manager button
  src/main/java/Server/ShopController.java
  src/main/java/Server/SystemController.java
  src/main/java/ServiceLayer/SystemService.java
  src/main/java/ServiceLayer/UserService.java
  src/main/java/UI/Model/PermissionMapper.java
  src/main/java/UI/Presenter/ShopManagerPresenter.java
  src/main/java/UI/View/ShopManagerView.java
Labels: start first with

#501 133 close store alert code ut and at code
  src/test/java/DomainTests/LiveAlertTests.java
Labels: bug
